# BNS (Bharatiya Nyaya Sanhita, 2023 - Act 14)
# Authentic Bare Act Marginal Headings for Generic Sections

BNS_TITLES = {
    "7": "Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple",
    "9": "Sentence in cases of conviction of several offences at one trial",
    "10": "Fractions of terms of punishment",
    "11": "Sentence of imprisonment for non-payment of fine",
    "12": "Limit to imprisonment for non-payment of fine, when offence punishable with imprisonment as well as fine",
    "13": "Description of imprisonment for non-payment of fine",
    "26": "Act done in good faith for benefit of child or person of unsound mind, by or by consent of guardian",
    "27": "Consent known to be given under fear or misconception",
    "28": "Consent of child, person of unsound mind or intoxicated person",
    "29": "Exclusion of acts which are offences independently of harm caused",
    "30": "Act done in good faith for benefit of a person without consent",
    "31": "Communication made in good faith",
    "32": "Act to which a person is compelled by threats",
    "33": "Act causing slight harm",
    "39": "Right of private defence against deadly assault when there is risk of harm to innocent person",
    "40": "Right of private defence of property",
    "42": "When right of private defence of property extends to causing any harm other than death",
    "43": "Commencement and continuance of right of private defence of property",
    "44": "Right of private defence against act of person of unsound mind, etc.",
    "48": "Liability of abettor when one act abetted and different act done",
    "50": "Abettor when liable to cumulative punishment for act abetted and for act done",
    "51": "Liability of abettor for an effect caused by the act abetted different from that intended by the abettor",
    "52": "Abettor present when offence is committed",
    "53": "Abetment of offence punishable with death or imprisonment for life",
    "54": "Abetment of offence punishable with imprisonment",
    "55": "Abetting commission of offence by the public or by more than ten persons",
    "56": "Concealing design to commit offence punishable with death or imprisonment for life",
    "57": "A public servant concealing design to commit offence which it is his duty to prevent",
    "58": "Concealing design to commit offence punishable with imprisonment",
    "59": "Harbouring offender",
    "60": "Screening offender or giving false information to screen offender",
    "73": "Cohabitation caused by a man deceitfully inducing a belief of lawful marriage",
    "81": "Assault or use of criminal force to woman with intent to disrobe",
    "82": "Voyeurism",
    "83": "Stalking",
    "84": "Word, gesture or act intended to insult modesty of a woman",
    "87": "Causing miscarriage without woman's consent",
    "88": "Death caused by act done with intent to cause miscarriage",
    "89": "Act done with intent to prevent child being born alive or to cause it to die after birth",
    "90": "Causing death of quick unborn child by act amounting to culpable homicide",
    "93": "Exposure and abandonment of child under twelve years of age by parent or person having care of it",
    "94": "Concealment of birth by secret disposal of dead body",
    "99": "Kidnapping or abducting child under ten years with intent to steal from its person",
    "104": "Causing death by negligence",
    "119": "Voluntarily causing grievous hurt by dangerous weapons or means",
    "120": "Voluntarily causing hurt to extort property, or to constrain to an illegal act",
    "121": "Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act",
    "122": "Voluntarily causing hurt to extort confession, or to compel restoration of property",
    "123": "Voluntarily causing grievous hurt to extort confession, or to compel restoration of property",
    "129": "Wrongful confinement for three or more days",
    "131": "Wrongful confinement of person for whose liberation writ has been issued",
    "133": "Wrongful confinement to extort property, or constrain to illegal act",
    "134": "Wrongful confinement to extort confession, or compel restoration of property",
    "135": "Assault or criminal force otherwise than on grave provocation",
    "136": "Assault or criminal force to deter public servant from discharge of his duty",
    "139": "Assault or criminal force on grave provocation",
    "141": "Kidnapping or abducting in order to murder",
    "142": "Kidnapping or abducting with intent secretly and wrongfully to confine person",
    "144": "Kidnapping or abducting child under ten years with intent to steal from its person",
    "145": "Trafficking of person",
    "146": "Unlawful compulsory labour",
    "149": "Collecting arms, etc., with intention of waging war against Government of India",
    "150": "Concealing with intent to facilitate design to wage war",
    "151": "Assaulting President, Governor, etc., with intent to compel or restrain exercise of any lawful power",
    "153": "Waging war against Government of any Asiatic Power in alliance with Government of India",
    "154": "Committing depredation on territories of Power at peace with Government of India",
    "155": "Receiving property taken by war or depredation mentioned in sections 153 and 154",
    "156": "Public servant voluntarily allowing prisoner of State or war to escape",
    "157": "Public servant negligently suffering such prisoner to escape",
    "158": "Aiding escape of, rescuing or harbouring such prisoner",
    "159": "Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty",
    "160": "Abetment of mutiny, if mutiny is committed in consequence thereof",
    "161": "Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office",
    "162": "Abetment of such assault, if the assault is committed",
    "163": "Abetment of desertion of soldier, sailor or airman",
    "164": "Harbouring deserter",
    "165": "Deserter concealed on board merchant vessel through negligence of master",
    "166": "Abetment of act of insubordination by soldier, sailor or airman",
    "167": "Persons subject to certain Acts not punishable under this Sanhita",
    "168": "Wearing garb or carrying token used by soldier, sailor or airman",
    "169": "Candidate, electoral right defined",
    "170": "Bribery at elections",
    "171": "Undue influence at elections",
    "172": "Personation at elections",
    "173": "Punishment for bribery at elections",
    "174": "Punishment for undue influence or personation at an election",
    "175": "False statement in connection with an election",
    "176": "Illegal payments in connection with an election",
    "177": "Failure to keep election accounts",
    "178": "Counterfeiting coin, government stamps, currency-notes or bank-notes",
    "179": "Using as genuine, forged or counterfeit coin, government stamp, currency-notes or bank-notes",
    "180": "Possession of forged or counterfeit coin, government stamp, currency-notes or bank-notes",
    "181": "Making or possessing instruments or materials for forging or counterfeiting coin, government stamp, currency-notes or bank-notes",
    "182": "Making or using documents resembling currency-notes or bank-notes",
    "183": "Effacing writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government",
    "184": "Using Government stamp known to have been before used",
    "185": "Erasure of mark denoting that stamp has been used",
    "186": "Fraudulent use of false instrument for weighing",
    "187": "Fraudulent use of false weight or measure",
    "188": "Being in possession of false weight or measure",
    "192": "Wantonly giving provocation with intent to cause riot",
    "193": "Owner or occupier of land on which an unlawful assembly is held",
    "194": "Liability of person for whose benefit riot is committed",
    "195": "Liability of agent of owner or occupier for whose benefit riot is committed",
    "198": "Public servant disobeying law, with intent to cause injury to any person",
    "199": "Public servant disobeying direction under law",
    "200": "Public servant framing an incorrect document with intent to cause injury",
    "201": "Public servant unlawfully engaging in trade",
    "202": "Public servant unlawfully buying or bidding for property",
    "203": "Personating a public servant",
    "204": "Wearing garb or carrying token used by public servant with fraudulent intent",
    "205": "Taking gift, etc., to screen an offender from punishment",
    "207": "Non-attendance in obedience to an order from public servant",
    "208": "Omission to produce document to public servant by person legally bound to produce it",
    "209": "Omission to give notice or information to public servant by person legally bound to give it",
    "210": "Furnishing false information to public servant",
    "211": "Refusing oath or affirmation when duly required by public servant to make it",
    "212": "Refusing to answer public servant authorized to question",
    "213": "Refusing to sign statement",
    "214": "False statement on oath or affirmation to public servant or person authorized to administer an oath",
    "215": "False information, with intent to cause public servant to use his lawful power to the injury of another person",
    "216": "Resistance to the taking of property by the lawful authority of a public servant",
    "217": "Obstructing sale of property offered for sale by authority of public servant",
    "218": "Illegal purchase or bid for property offered for sale by authority of public servant",
    "219": "Obstructing public servant in discharge of public functions",
    "220": "Omission to assist public servant when bound by law to give assistance",
    "221": "Disobedience to order duly promulgated by public servant",
    "222": "Threat of injury to public servant",
    "224": "Threat of injury to induce person to refrain from applying for protection to public servant",
    "225": "Intentional insult or interruption to public servant sitting in judicial proceeding",
    "226": "Attempt to commit suicide to compel or restrain exercise of lawful power",
    "230": "Giving false evidence",
    "231": "Fabricating false evidence",
    "232": "Punishment for false evidence",
    "233": "Giving or fabricating false evidence with intent to procure conviction of capital offence",
    "234": "Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment",
    "235": "Threatening any person to give false evidence",
    "236": "Using evidence known to be false",
    "237": "Issuing or signing false certificate",
    "239": "Using as true a certificate known to be false",
    "240": "False statement made in declaration which is by law receivable as evidence",
    "241": "Using as true such declaration knowing it to be false",
    "242": "False claim in Court",
    "243": "Fraudulently obtaining decree for sum not due",
    "244": "Dishonestly making false claim in Court",
    "245": "Fraudulently suffering decree for sum not due",
    "246": "Dishonest or fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution",
    "247": "Dishonest or fraudulent claim to property to prevent its seizure as forfeited or in execution",
    "248": "Fraudulent suffering decree for sum not due",
    "249": "False charge of offence made with intent to injure",
    "250": "Harbouring offender",
    "251": "Taking gift, etc., to screen an offender from punishment",
    "252": "Offering gift or restoration of property in consideration of screening offender",
    "253": "Taking gift to help to recover stolen property, etc.",
    "254": "Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture",
    "255": "Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture",
    "256": "Public servant in judicial proceeding corruptly making report, etc., contrary to law",
    "257": "Commitment for trial or confinement by person having authority who knows that he is acting contrary to law",
    "258": "Intentional omission to apprehend on the part of public servant bound to apprehend",
    "259": "Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence or lawfully committed",
    "260": "Escape from confinement or custody negligently suffered by public servant",
    "261": "Resistance or obstruction by a person to his lawful apprehension",
    "262": "Resistance or obstruction to lawful apprehension of another person",
    "263": "Escape from custody or failure to appear in Court",
    "264": "Violation of condition of remission of punishment",
    "265": "Intentional insult or interruption to public servant sitting in judicial proceeding",
    "266": "Personation of an assessor or juror",
    "267": "Disclosure of identity of victim of certain offences, etc.",
    "268": "Failure by person released on bail or bond to appear in court",
    "271": "Negligent act likely to spread infection of disease dangerous to life",
    "272": "Malignant act likely to spread infection of disease dangerous to life",
    "273": "Disobedience to quarantine rule",
    "274": "Adulteration of food or drink intended for sale",
    "275": "Sale of noxious food or drink",
    "276": "Adulteration of drugs",
    "277": "Sale of adulterated drugs",
    "278": "Sale of drug as a different drug or preparation",
    "279": "Fouling water of public spring or reservoir",
    "280": "Making atmosphere noxious to health",
    "282": "Rash navigation of vessel",
    "283": "Exhibition of false light, mark or buoy",
    "284": "Conveying person by water for hire in unsafe or overloaded vessel",
    "285": "Danger or obstruction in public way or line of navigation",
    "286": "Negligent conduct with respect to poisonous substance",
    "287": "Negligent conduct with respect to fire or combustible matter",
    "288": "Negligent conduct with respect to explosive substance",
    "289": "Negligent conduct with respect to machinery",
    "290": "Negligent conduct with respect to pulling down or repairing buildings",
    "291": "Negligent conduct with respect to animal",
    "292": "Punishment for public nuisance in cases not otherwise provided for",
    "293": "Continuance of nuisance after injunction to discontinue",
    "294": "Sale, etc., of obscene books, etc.",
    "295": "Sale, etc., of obscene objects to young person",
    "296": "Obscene acts and songs",
    "297": "Keeping lottery office",
    "300": "Injuring or defiling place of worship with intent to insult the religion of any class",
    "301": "Disturbing religious assembly",
    "302": "Uttering words, etc., with deliberate intent to wound religious feelings of any person",
    "306": "Theft in dwelling house, etc.",
    "307": "Theft by clerk or servant of property in possession of master",
    "312": "Putting person in fear of death or grievous hurt in order to commit extortion",
    "313": "Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc.",
    "314": "Robbery",
    "315": "Dacoity",
    "319": "Misappropriation of property",
    "320": "Dishonest misappropriation of property possessed by deceased person at the time of his death",
    "321": "Criminal breach of trust by carrier, wharfinger or warehouse keeper",
    "322": "Criminal breach of trust by clerk or servant",
    "323": "Criminal breach of trust by public servant, or by banker, merchant or agent",
    "325": "Stolen property",
    "326": "Habitually dealing in stolen property",
    "327": "Cheating",
    "328": "Cheating by personation",
    "330": "Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect",
    "331": "Cheating and dishonestly inducing delivery of property",
    "332": "Dishonest or fraudulent execution of deed of transfer containing false statement of consideration",
    "333": "Dishonest or fraudulent removal or concealment of property",
    "334": "Mischief",
    "337": "Forgery of record of Court or of public register, etc.",
    "339": "Having possession of document described in section 337 or 338 knowing it to be forged and intending to use it as genuine",
    "341": "Counterfeiting device or mark used for authenticating documents described in section 338, or possessing counterfeit marked material",
    "342": "Counterfeiting device or mark used for authenticating documents other than those described in section 338, or possessing counterfeit marked material",
    "343": "Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security",
    "344": "Falsification of accounts",
    "345": "Property mark",
    "346": "Using a false property mark",
    "347": "Punishment for using a false property mark",
    "348": "Counterfeiting a property mark used by another",
    "349": "Counterfeiting a mark used by a public servant",
    "350": "Making or possession of any instrument for counterfeiting a property mark",
    "353": "Statements conducing to public mischief",
    "354": "Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure",
    "355": "Criminal intimidation by an anonymous communication",
    "357": "Word, gesture or act intended to insult the modesty of a woman"
}
