# BNSS (Bharatiya Nagarik Suraksha Sanhita, 2023 - Act 15)
# Authentic Bare Act Marginal Headings for Generic Sections

BNSS_TITLES = {
    # Preliminary
    "3": "Construction of references",
    "4": "Trial of offences under Bharatiya Nyaya Sanhita and other laws",
    "5": "Saving",
    # Constitution of Criminal Courts
    "7": "Territorial divisions",
    "11": "Special Judicial Magistrates",
    "12": "Local Jurisdiction of Judicial Magistrates",
    "13": "Subordination of Judicial Magistrates",
    "14": "Executive Magistrates",
    "15": "Special Executive Magistrates",
    "16": "Local Jurisdiction of Executive Magistrates",
    "17": "Subordination of Executive Magistrates",
    "19": "Public Prosecutors",
    "20": "Assistant Public Prosecutors",
    # Power of Courts
    "24": "Sentence in default of fine",
    "25": "Sentence in cases of conviction of several offences at one trial",
    "26": "Mode of conferring powers",
    "27": "Powers of officers appointed",
    "28": "Withdrawal of powers",
    "29": "Powers of Judges and Magistrates exercisable by their successors-in-office",
    "30": "Public when to assist Magistrates and police",
    # Powers of Superior Officers & Aid
    "31": "Powers of superior officers of police",
    "32": "Aid to person, other than police officer, executing warrant",
    "33": "Public to give information of certain offences",
    "34": "Duty of officers employed in connection with affairs of a village to make certain report",
    # Arrest of Persons
    "39": "Arrest on refusal to give name and residence",
    "40": "Arrest by private person and procedure on such arrest",
    "41": "Arrest by Magistrate",
    "42": "Protection of members of Armed Forces from arrest",
    "44": "Search of place entered by person sought to be arrested",
    "45": "Pursuit of offenders into other jurisdictions",
    "46": "No unnecessary restraint",
    "47": "Person arrested to be informed of grounds of arrest and of right to bail",
    "48": "Obligation of person making arrest to inform about the arrest, etc., to a nominated person",
    "49": "Search of arrested person",
    "50": "Power to seize offensive weapons",
    "51": "Examination of accused by medical practitioner at request of police officer",
    "52": "Examination of person accused of rape by medical practitioner",
    "53": "Examination of arrested person by medical officer",
    "54": "Identification of person arrested",
    "55": "Procedure when police officer deputes subordinate to arrest without warrant",
    "56": "Health and safety of arrested person",
    "57": "Person arrested to be taken before Magistrate or officer in charge of police station",
    "59": "Police to report apprehensions",
    "60": "Discharge of person apprehended",
    "61": "Power, on escape, to pursue and retake",
    "62": "Arrest to be made strictly according to the Sanhita",
    # Processes to Compel Appearance
    "65": "Service of summons on corporate bodies, firms and societies",
    "66": "Service when persons summoned cannot be found",
    "67": "Procedure when service cannot be effected as before provided",
    "68": "Service on Government servant",
    "69": "Service of summons outside local limits",
    "70": "Proof of service in such cases and when serving officer not present",
    "71": "Service of summons on witness by post or electronic means",
    "72": "Form of warrant of arrest and duration",
    "73": "Power to direct security to be taken",
    "74": "Warrants to whom directed",
    "75": "Warrant may be directed to any person",
    "76": "Warrant directed to police officer",
    "77": "Notification of substance of warrant",
    "78": "Person arrested to be brought before Court without delay",
    "79": "Where warrant may be executed",
    "80": "Warrant forwarded for execution outside jurisdiction",
    "81": "Warrant directed to police officer for execution outside jurisdiction",
    "82": "Procedure on arrest of person against whom warrant issued",
    "83": "Procedure by Magistrate before whom such person arrested is brought",
    "85": "Attachment of property of person absconding",
    "86": "Claims and objections to attachment",
    "87": "Release, sale and restoration of attached property",
    "88": "Appeal from order rejecting application for restoration of attached property",
    "89": "Issue of warrant in lieu of, or in addition to, summons",
    "90": "Power to take bond for appearance",
    "91": "Arrest on breach of bond for appearance",
    "92": "Provisions of this Chapter generally applicable to summonses and warrants of arrest",
    "93": "Reciprocal arrangements regarding processes",
    # Processes to Compel Production of Things
    "95": "Procedure as to letters and telegrams",
    "96": "When search-warrant may be issued",
    "97": "Search of place suspected to contain stolen property, forged documents, etc.",
    "98": "Power to declare certain publications forfeited and to issue search-warrants for the same",
    "99": "Application to High Court to set aside declaration of forfeiture",
    "100": "Search for persons wrongfully confined",
    "101": "Power to compel restoration of abducted females",
    "102": "Direction, etc., of search-warrants",
    "103": "Persons in charge of closed place to allow search",
    "104": "Disposal of things found in search beyond jurisdiction",
    "105": "Recording of search and seizure through audio-video electronic means",
    "106": "Power of police officer to seize certain property",
    "108": "Magistrate may direct search in his presence",
    "109": "Power to impound document, etc., produced",
    "110": "Reciprocal arrangements regarding processes",
    # Reciprocal Arrangements
    "111": "Definitions",
    "112": "Special provisions regarding warrant of arrest and search-warrant",
    "113": "Letter of request to competent authority for investigation in a country or place outside India",
    "114": "Letter of request from a country or place outside India to a Court or an authority for investigation in India",
    "115": "Assistance in securing transfer of persons",
    "116": "Assistance in relation to orders of attachment or forfeiture of property",
    "117": "Identifying unlawfully acquired property",
    "118": "Seizure or attachment of property",
    "119": "Management of properties seized or forfeited under this Chapter",
    "120": "Notice of forfeiture of property",
    "121": "Forfeiture of property in certain cases",
    "122": "Fine in lieu of forfeiture",
    "123": "Certain transfers to be null and void",
    "124": "Procedure in respect of letter of request",
    # Security for Keeping Peace & Good Behaviour
    "125": "Security for keeping the peace on conviction",
    "126": "Security for keeping the peace in other cases",
    "127": "Security for good behaviour from persons disseminating seditious matters",
    "128": "Security for good behaviour from suspected persons",
    "129": "Security for good behaviour from habitual offenders",
    "130": "Order to be made",
    "131": "Procedure in respect of person present in Court",
    "132": "Summons or warrant in case of person not so present",
    "133": "Copy of order to accompany summons or warrant",
    "134": "Power to dispense with personal attendance",
    "135": "Inquiry as to truth of information",
    "136": "Order to give security",
    "137": "Discharge of person informed against",
    "138": "Commencement of period for which security is required",
    "139": "Contents of bond",
    "140": "Power to reject sureties",
    "141": "Imprisonment in default of security",
    "142": "Power to release persons imprisoned for failing to give security",
    "143": "Security for unexpired period of bond",
    # Maintenance of Wives, Children and Parents
    "145": "Procedure",
    "146": "Alteration in allowance",
    "147": "Enforcement of order of maintenance",
    # Maintenance of Public Order and Tranquillity
    "148": "Dispersal of assembly by use of civil force",
    "149": "Use of armed forces to disperse assembly",
    "150": "Power of certain armed force officers to disperse assembly",
    "151": "Protection against prosecution for acts done under preceding sections",
    "152": "Conditional order for removal of nuisance",
    "153": "Service or notification of order",
    "154": "Person to whom order is addressed to obey or show cause",
    "155": "Consequences of his failing to do so",
    "156": "Procedure where existence of public right is denied",
    "157": "Procedure where he appears to show cause",
    "158": "Power of Magistrate to direct local investigation and examination of an expert",
    "159": "Power of Magistrate to furnish written instructions, etc.",
    "160": "Procedure on order being made absolute and consequences of disobedience",
    "161": "Injunction pending inquiry",
    "162": "Magistrate may prohibit repetition or continuance of public nuisance",
    "164": "Power to prohibit carrying arms in procession or mass drill or mass training with arms",
    "165": "Procedure where dispute concerning land or water is likely to cause breach of peace",
    "166": "Power to attach subject of dispute and to appoint receiver",
    "167": "Dispute concerning right of use of land or water",
    # Preventive Action of the Police
    "168": "Police to prevent cognizable offences",
    "169": "Information of design to commit cognizable offences",
    "170": "Arrest to prevent the commission of cognizable offences",
    "171": "Prevention of injury to public property",
    "172": "Inspection of weights and measures",
    # Information to Police & Investigation
    "177": "Report how submitted",
    "178": "Power to hold investigation or preliminary inquiry",
    "179": "Police officer's power to require attendance of witnesses",
    "181": "No inducement to be offered",
    "182": "Recording of confessions and statements",
    "184": "Examination of person accused of rape by medical practitioner",
    "185": "Search by police officer",
    "186": "When officer in charge of police station may require another to issue search-warrant",
    "188": "Report of investigation by subordinate police officer",
    "189": "Release of accused when evidence deficient",
    "190": "Cases to be sent to Magistrate, when evidence is sufficient",
    "191": "Complainant and witnesses not to be required to accompany police officer and not to be subjected to restraint",
    "192": "Diary of proceedings in investigation",
    "194": "Police to inquire and report on suicide, etc.",
    "195": "Power to summon persons",
    "196": "Inquiry by Magistrate into cause of death",
    # Jurisdiction in Inquiries and Trials
    "197": "Ordinary place of inquiry and trial",
    "198": "Place of inquiry or trial",
    "199": "Offence triable where act is done or consequence ensues",
    "200": "Place of trial where act is an offence by reason of relation to other offence",
    "201": "Place of trial in case of certain offences",
    "202": "Offences committed by letters, etc.",
    "203": "Offence committed on journey or voyage",
    "204": "Place of trial for offences triable together",
    "205": "Power to order cases to be tried in different sessions divisions",
    "206": "High Court to decide, in case of doubt, district where inquiry or trial shall take place",
    "207": "Power to issue summons or warrant for offence committed beyond local jurisdiction",
    "208": "Offence committed outside India",
    "209": "Receipt of evidence relating to offences committed outside India",
    # Initiation of Proceedings
    "211": "Transfer on application of the accused",
    "212": "Making over of cases to Magistrates",
    "213": "Prosecution for contempt of lawful authority of public servants, for offences against public justice and for offences relating to documents given in evidence",
    "214": "Additional and Assistant Sessions Judges to try cases made over to them",
    "215": "Prosecution for offences against the State and for criminal conspiracy to commit such offence",
    "216": "Prosecution of Judges and public servants",
    "217": "Prosecution for offences against marriage",
    "218": "Prosecution of offences under section 84 of the Bharatiya Nyaya Sanhita, 2023",
    "219": "Prosecution for defamation",
    "220": "Cognizance of offence by Court of Session",
    "221": "Cognizance of offence on complaint by public servant",
    "222": "Cognizance of offence by Magistrate on complaint",
    # Complaints to Magistrates
    "224": "Procedure by Magistrate not competent to take cognizance of the case",
    "225": "Postponement of issue of process",
    "226": "Dismissal of complaint",
    # Commencement of Proceedings Before Magistrates
    "227": "Issue of process",
    "228": "Magistrate may dispense with personal attendance of accused",
    "229": "Special summons in case of petty offence",
    "231": "Supply of copies of statements and documents to accused in other cases triable by Court of Session",
    "233": "Procedure to be followed when there is a complaint case and police investigation in respect of the same offence",
    # The Charge
    "234": "Contents of charge",
    "235": "Particulars as to time, place and person",
    "236": "When manner of committing offence must be stated",
    "237": "Words in charge taken in sense of law under which offence is punishable",
    "238": "Effect of errors",
    "239": "Court may alter charge",
    "240": "Recall of witnesses when charge altered",
    "241": "Separate charges for distinct offences",
    "242": "Three offences of same kind within year may be charged together",
    "243": "Trial for more than one offence",
    "244": "Where it is doubtful what offence has been committed",
    "245": "When offence proved included in offence charged",
    "246": "What persons may be charged jointly",
    "247": "Withdrawal of remaining charges on conviction on one of several charges",
    # Sessions Trial
    "248": "Trial to be conducted by Public Prosecutor",
    "249": "Opening case for prosecution",
    "252": "Conviction on plea of guilty",
    "253": "Date for prosecution evidence",
    "254": "Evidence for prosecution",
    "255": "Acquittal",
    "256": "Entering upon defence",
    "257": "Arguments",
    "259": "Previous conviction",
    "260": "Procedure in cases instituted under section 219(2)",
    # Warrant Cases by Magistrates
    "261": "Compliance with section 230",
    "262": "When accused shall be discharged",
    "263": "Framing of charge",
    "264": "Conviction on plea of guilty",
    "265": "Evidence for prosecution",
    "266": "Evidence for defence",
    "267": "Evidence for prosecution (in cases instituted otherwise than on police report)",
    "268": "When accused shall be discharged",
    "269": "Procedure where accused is not discharged",
    "270": "Evidence for defence",
    "271": "Acquittal or conviction",
    "272": "Absence of complainant",
    "273": "Compensation for accusation without reasonable cause",
    # Summons Cases by Magistrates
    "274": "Substance of accusation to be stated",
    "275": "Conviction on plea of guilty",
    "276": "Conviction on plea of guilty in absence of accused in petty cases",
    "277": "Procedure when not convicted",
    "278": "Acquittal or conviction",
    "279": "Non-appearance or death of complainant",
    "280": "Withdrawal of complaint",
    "281": "Power to stop proceedings in certain cases",
    "282": "Power of Court to convert summons-cases into warrant-cases",
    # Summary Trials
    "283": "Power to try summarily",
    "284": "Summary trial by Magistrate of the second class",
    "285": "Procedure for summary trials",
    "286": "Record in summary trials",
    "287": "Judgment in cases tried summarily",
    "288": "Language of record and judgment",
    # Plea Bargaining
    "290": "Application of the Chapter",
    "291": "Application for plea bargaining",
    "292": "Guidelines for mutually satisfactory disposition",
    "293": "Report of the mutually satisfactory disposition to be submitted before the Court",
    "294": "Disposal of the case",
    "295": "Judgment of the Court",
    "296": "Finality of the judgment",
    "297": "Power of the Court in plea bargaining",
    "298": "Period of detention undergone by the accused to be set off against the sentence of imprisonment",
    "299": "Savings",
    "300": "Statements of accused not to be used",
    # Attendance of Prisoners
    "301": "Definitions",
    "302": "Power to require attendance of prisoners",
    "303": "Power of State Government to exclude certain persons from operation of section 302",
    "304": "Officer in charge of prison to abstain from carrying out order in certain contingencies",
    "305": "Prisoner to be brought to Court in custody",
    "306": "Power to issue commission for examination of witness in prison",
    # Evidence in Inquiries and Trials
    "307": "Language of Courts",
    "308": "Evidence to be taken in presence of accused",
    "309": "Record in summons-cases and inquiries",
    "310": "Record in warrant-cases",
    "311": "Record in trial before Court of Session",
    "312": "Language of record of evidence",
    "313": "Procedure in regard to such evidence when completed",
    "314": "Interpretation of evidence to accused or his pleader",
    "315": "Remarks respecting demeanour of witness",
    "316": "Record of examination of accused",
    "317": "Interpreter to be bound to interpret truthfully",
    "318": "Record in High Court",
    "319": "When attendance of witness may be dispensed with and commission issued",
    "320": "Commission to whom to be issued",
    "321": "Execution of commissions",
    "322": "Parties may examine witnesses",
    "323": "Return of commission",
    "324": "Adjournment of proceeding",
    "325": "Execution of foreign commissions",
    "326": "Deposition of medical witness",
    "327": "Identification report of Magistrate",
    "328": "Evidence of officers of the Mint",
    "329": "Reports of certain Government scientific experts",
    "330": "No formal proof of certain documents",
    "331": "Affidavit in proof of conduct of public servants",
    "332": "Evidence of formal character on affidavit",
    "333": "Authorities before whom affidavits may be sworn",
    "334": "Previous conviction or acquittal how proved",
    "335": "Record of evidence in absence of accused",
    "336": "Evidence of public servant, expert, etc., through audio-video electronic means",
    # General Provisions as to Inquiries and Trials
    "337": "Person once convicted or acquitted not to be tried for same offence",
    "338": "Appearance by Public Prosecutors",
    "339": "Permission to conduct prosecution",
    "340": "Right of person against whom proceedings are instituted to be defended",
    "341": "Legal aid to accused at State expense in certain cases",
    "342": "Procedure when corporation or registered society is an accused",
    "343": "Tender of pardon to accomplice",
    "344": "Power to direct tender of pardon",
    "345": "Trial of person not complying with conditions of pardon",
    "346": "Power to postpone or adjourn proceedings",
    "347": "Local inspection",
    "348": "Power to summon material witness, or examine person present",
    "349": "Power to examine the accused",
    "350": "Oral arguments and memorandum of arguments",
    "351": "Accused person to be competent witness",
    "352": "No influence to be used to induce disclosure",
    "353": "Provision for inquiries and trial being held in the absence of accused in certain cases",
    "354": "Procedure where accused does not understand proceedings",
    "355": "Power to proceed against other persons appearing to be guilty of offence",
    "356": "Inquiry, trial or judgment in absentia of proclaimed offender",
    "357": "Compounding of offences",
    "358": "Power of Court to convert summons-cases into warrant-cases",
    "359": "Procedure in cases which Magistrate cannot dispose of",
    "360": "Procedure when, after Commencement of inquiry or trial, Magistrate finds case should be committed",
    "361": "Trial of persons previously convicted of offences against coinage, stamp-law or property",
    "362": "Procedure when Magistrate cannot pass sentence sufficiently severe",
    "363": "Conviction or commitment on evidence partly recorded by one Magistrate and partly by another",
    "364": "Court to be open",
    "365": "Withdrawal from prosecution",
    "366": "Expenses of complainants and witnesses",
    # Accused Persons of Unsound Mind
    "367": "Procedure in case of accused being lunatic",
    "368": "Procedure in case of person of unsound mind tried before Court",
    "369": "Release of person of unsound mind pending investigation or trial",
    "370": "Resumption of inquiry or trial",
    "371": "Procedure on accused appearing before Magistrate or Court",
    "372": "When accused appears to have been of sound mind",
    "373": "Judgment of acquittal on ground of unsoundness of mind",
    "374": "Person acquitted on such ground to be detained in safe custody",
    "375": "Power of State Government to empower officer in charge to discharge",
    "376": "Procedure where lunatic prisoner is reported capable of making his defence",
    "377": "Procedure where lunatic detained is declared fit to be released",
    "378": "Delivery of lunatic to care of relative or friend",
    # Offences Affecting Administration of Justice
    "379": "Procedure in cases mentioned in section 213",
    "380": "Appeal",
    "381": "Power to order costs",
    "382": "Procedure of Magistrate taking cognizance",
    "383": "Summary procedure for trial for giving false evidence",
    "384": "Procedure in certain cases of contempt",
    "385": "Procedure where Court considers that case should not be dealt with under section 384",
    "386": "When Registrar or Sub-Registrar to be deemed a Civil Court",
    "387": "Discharge of offender on submission of apology",
    "388": "Imprisonment or committal of person refusing to answer or produce document",
    "389": "Summary procedure for punishment for non-attendance by a witness in obedience to summons",
    "390": "Appeals from convictions under sections 383, 384, 388 and 389",
    "391": "Certain Judges and Magistrates not to try certain offences when committed before themselves",
    # The Judgment
    "393": "Language and contents of judgment",
    "394": "Order to pay costs in non-cognizable cases",
    "395": "Order to release on probation of good conduct or after admonition",
    "397": "Compensation to persons groundlessly arrested",
    "398": "Order to pay costs in non-cognizable cases",
    "399": "Order to release on probation of good conduct or after admonition",
    "400": "Special reasons to be recorded in certain cases",
    "401": "Court not to alter judgment",
    "402": "Copy of judgment to be given to the accused and other persons",
    "403": "Judgment when to be translated",
    "404": "Court of Session to send copy of finding and sentence to District Magistrate",
    "405": "Postponement of capital sentence on pregnant woman",
    "406": "Power to appoint place of imprisonment",
    # Confirmation of Death Sentences
    "407": "Sentence of death to be submitted by Court of Session for confirmation",
    "408": "Power to direct further inquiry to be made or additional evidence to be taken",
    "409": "Power of High Court to confirm sentence or annul conviction",
    "410": "Confirmation or new sentence to be signed by two Judges",
    "411": "Procedure in case of difference of opinion",
    "412": "Procedure in cases submitted to High Court for confirmation",
    # Appeals
    "414": "Appeal from orders requiring security or refusal to accept or rejecting surety for keeping peace or good behaviour",
    "415": "Appeals from convictions",
    "416": "No appeal in certain cases when accused pleads guilty",
    "417": "No appeal in petty cases",
    "418": "Appeal by the State Government against sentence",
    "419": "Appeal in case of acquittal",
    "420": "Appeal against conviction by High Court in certain cases",
    "421": "Special right of appeal in certain cases",
    "422": "Appeal to Court of Session how heard",
    "423": "Petition of appeal",
    "424": "Procedure when appellant in jail",
    "425": "Summary dismissal of appeal",
    "426": "Procedure for hearing appeals not dismissed summarily",
    "427": "Powers of the Appellate Court",
    "428": "Judgments of Subordinate Appellate Court",
    "429": "Order of High Court on appeal to be certified to lower Court",
    "430": "Suspension of sentence pending the appeal; release of appellant on bail",
    "431": "Arrest of accused in appeal from acquittal",
    "432": "Appellate Court may take further evidence or direct it to be taken",
    "433": "Procedure where Judges of Court of Appeal are equally divided",
    "434": "Finality of judgments and orders on appeal",
    "435": "Abatement of appeals",
    # Reference and Revision
    "436": "Reference to High Court",
    "437": "Disposal of case according to decision of High Court",
    "438": "Calling for records to exercise powers of revision",
    "439": "Power to order inquiry",
    "440": "Sessions Judge's powers of revision",
    "441": "Power of Additional Sessions Judge",
    "442": "High Court's powers of revision",
    "443": "Power of High Court to withdraw or transfer revision cases",
    "444": "Option of Court to hear parties",
    "445": "High Court's order to be certified to lower Court",
    # Transfer of Cases
    "446": "Power of Supreme Court to transfer cases and appeals",
    "447": "Power of High Court to transfer cases and appeals",
    "448": "Power of Sessions Judge to transfer cases and appeals",
    "449": "Withdrawal of cases and appeals by Sessions Judge",
    "450": "Withdrawal of cases by Judicial Magistrates",
    "451": "Making over or withdrawal of cases by Executive Magistrates",
    "452": "Reasons to be recorded",
    # Execution of Sentences
    "453": "Execution of order passed under section 409",
    "454": "Execution of sentence of death passed by High Court",
    "455": "Postponement of execution of sentence of death in case of appeal to Supreme Court",
    "456": "Postponement of capital sentence on pregnant woman",
    "457": "Power to appoint place of imprisonment",
    "458": "Execution of sentence of imprisonment",
    "459": "Direction of warrant for execution",
    "460": "Warrant with whom to be lodged",
    "461": "Warrant for levy of fine",
    "462": "Effect of such warrant",
    "463": "Warrant for levy of fine issued by a Court in any territory to which this Sanhita does not extend",
    "464": "Suspension of execution of sentence of imprisonment",
    "465": "Who may issue warrant",
    "466": "Sentence on escaped convict when to take effect",
    "467": "Sentence on offender already sentenced for another offence",
    "468": "Period of detention undergone by the accused to be set off against the sentence of imprisonment",
    "469": "Saving",
    "470": "Return of warrant on execution of sentence",
    "471": "Money ordered to be paid recoverable as a fine",
    "472": "Power to suspend or remit sentences",
    "473": "Power to commute sentence",
    "474": "Concurrent power of Central Government in case of death sentences",
    "475": "State Government to act after consultation with Central Government in certain cases",
    "476": "Restriction on powers of remission or Commutation in certain cases",
    "477": "Power of Central Government to make rules",
    # Bail and Bonds
    "478": "In what cases bail to be taken",
    "481": "Special powers of High Court or Court of Session regarding bail",
    "484": "Amount of bond and reduction thereof",
    "485": "Bond of accused and sureties",
    "486": "Declaration by surety",
    "487": "Discharge from custody",
    "488": "Power to order sufficient bail when that first taken is insufficient",
    "489": "Discharge of sureties",
    "490": "Deposit instead of recognizance",
    "491": "Procedure when bond has been forfeited",
    "492": "Cancellation of bond and bail bond",
    "493": "Procedure in case of insolvency or death of surety or when a bond is forfeited",
    "494": "Bond required from minor",
    "495": "Appeal from orders under section 491",
    "496": "Power to direct levy of amount due on certain recognizances",
    # Disposal of Property
    "497": "Order for custody and disposal of property pending inquiry or trial",
    "498": "Order for disposal of property at conclusion of trial",
    "499": "Payment to innocent purchaser of money found on accused",
    "500": "Appeal against orders under section 498 or section 499",
    "501": "Destruction of libellous and other matter",
    "502": "Power to restore possession of immovable property",
    "503": "Procedure by police upon seizure of property",
    "504": "Procedure where no claimant appears within six months",
    "505": "Power to sell perishable property",
    # Irregular Proceedings
    "506": "Irregularities which do not vitiate proceedings",
    "507": "Irregularities which vitiate proceedings",
    "508": "Proceedings in wrong place",
    "509": "Non-compliance with provisions of section 182 or section 316",
    "510": "Effect of omission to frame, or absence of, or error in, charge",
    "511": "Finding or sentence when reversible by reason of error, omission or irregularity",
    "512": "Defect or want of form in proceedings",
    # Limitation
    "513": "Definitions",
    "514": "Bar to taking cognizance after lapse of the period of limitation",
    "515": "Commencement of the period of limitation",
    "516": "Exclusion of time in certain cases",
    "517": "Exclusion of date on which Court is closed",
    "518": "Continuing offence",
    "519": "Extension of period of limitation in certain cases",
    # Miscellaneous
    "520": "Trials before High Courts",
    "521": "Delivery to commanding officers of persons liable to be tried by Court-martial",
    "522": "Forms",
    "523": "Power of High Court to make rules",
    "524": "Power to alter functions allocated to Executive Magistrates in certain cases",
    "525": "Case in which Judge or Magistrate is personally interested",
    "526": "Practising pleader not to sit as Magistrate in certain Courts",
    "527": "Public servant concerned in sale not to purchase or bid for property",
    "529": "Duty of High Court to exercise continuous superintendence over Courts of Judicial Magistrates"
}
