# BSA (Bharatiya Sakshya Adhiniyam, 2023 - Act 16)
# Authentic Bare Act Marginal Headings for Generic Sections

BSA_TITLES = {
    "10": "Facts not otherwise relevant become relevant (Plea of Alibi)",
    "11": "In suits for damages, facts tending to enable Court to determine amount are relevant",
    "13": "Facts bearing on question whether act was accidental or intentional",
    "14": "Existence of course of business when relevant",
    "16": "Admission by person whose position must be proved as against party to suit",
    "17": "Admissions by persons expressly referred to by party to suit",
    "18": "Proof of admissions against persons making them, and by or on their behalf",
    "19": "When oral admissions as to contents of documents are relevant",
    "20": "Admissions in civil cases when relevant",
    "25": "Confession otherwise relevant not to become irrelevant because of promise of secrecy, etc.",
    "27": "Admissions not conclusive proof, but may estop",
    "28": "Entries in books of account including those maintained in an electronic form when relevant",
    "29": "Relevancy of entry in public record made in performance of duty",
    "30": "Relevancy of statements in maps, charts and plans",
    "31": "Relevancy of statement as to fact of public nature contained in certain Acts or notifications",
    "32": "Relevancy of statements as to any law contained in law-books",
    "33": "What evidence to be given when statement forms part of a conversation, document, electronic record, book or series of letters or papers",
    "34": "Previous judgments relevant to bar a second suit or trial (Res Judicata)",
    "35": "Relevancy of certain judgments in probate, etc., jurisdiction (Judgments in rem)",
    "36": "Relevancy and effect of judgments, orders or decrees, other than those mentioned in section 35",
    "37": "Judgments, etc., other than those mentioned in sections 34 to 36, when relevant",
    "38": "Fraud or collusion in obtaining judgment, or incompetency of Court, may be proved",
    "43": "Facts bearing upon opinions of experts",
    "44": "Opinion as to handwriting and signature, when relevant",
    "45": "Opinion as to existence of right or custom, when relevant",
    "46": "Opinion as to usages, tenets, etc., when relevant",
    "47": "Opinion on relationship, when relevant",
    "48": "Grounds of opinion, when relevant",
    "64": "Rules as to notice to produce",
    "67": "Proof of execution of document required by law to be attested",
    "68": "Proof where no attesting witness found",
    "69": "Admission of execution by party to attested document",
    "70": "Proof when attesting witness denies the execution",
    "72": "Proof of document not required by law to be attested",
    "73": "Comparison of signature, writing or seal with others admitted or proved",
    "77": "Proof of documents by production of certified copies",
    "78": "Proof of other official documents",
    "80": "Presumption as to documents produced as record of evidence",
    "81": "Presumption as to Gazettes, newspapers, and other documents",
    "82": "Presumption as to Gazettes in electronic forms",
    "83": "Presumption as to maps or plans made by authority of Government",
    "84": "Presumption as to collections of laws and reports of decisions",
    "85": "Presumption as to powers-of-attorney",
    "89": "Presumption as to electronic messages",
    "90": "Presumption as to due execution, etc., of documents not produced",
    "91": "Presumption as to documents thirty years old",
    "96": "Exclusion of evidence to explain or amend ambiguous document",
    "97": "Exclusion of evidence against application of document to existing facts",
    "98": "Evidence as to document unmeaning in reference to existing facts",
    "99": "Evidence as to application of language which can apply to one only of several persons",
    "100": "Evidence as to application of language to one of two sets of facts, to neither of which the whole correctly applies",
    "101": "Evidence as to meaning of illegible characters, etc.",
    "102": "Who may give evidence of agreement varying terms of document",
    "103": "Saving of provisions of Indian Succession Act relating to wills",
    "112": "Burden of proof as to relationship in the cases of partners, landlord and tenant, principal and agent",
    "113": "Burden of proof as to ownership",
    "114": "Proof of good faith in transactions where one party is in relation of active confidence",
    "115": "Birth during marriage, conclusive proof of legitimacy",
    "122": "Estoppel of tenant and of licensee of person in possession",
    "123": "Estoppel of acceptor of bill of exchange, bailee or licensee",
    "127": "Privilege not waived by volunteering evidence",
    "131": "Production of documents or electronic records which another person, having possession, could refuse to produce",
    "133": "Accomplice",
    "134": "Number of witnesses",
    "135": "Order of production and examination of witnesses",
    "136": "Judge to decide as to admissibility of evidence",
    "143": "Cross-examination of person called to produce a document",
    "144": "Witnesses to character",
    "146": "Evidence as to matters in writing",
    "147": "Cross-examination as to previous statements in writing",
    "149": "When witness to be compelled to answer",
    "150": "Court to decide when question shall be asked and when witness compelled to answer",
    "151": "Question not to be asked without reasonable grounds",
    "152": "Procedure of Court in case of question being asked without reasonable grounds",
    "153": "Indecent and scandalous questions",
    "154": "Questions intended to insult or annoy",
    "155": "Exclusion of evidence to contradict answers to questions testing veracity",
    "156": "Question by party to his own witness",
    "158": "Questions tending to corroborate evidence of relevant fact, admissible",
    "159": "Former statements of witness may be proved to corroborate later testimony as to same fact",
    "160": "What matters may be proved in connection with proved statement relevant under section 26 or 27",
    "161": "Refreshing memory",
    "162": "Testimony to facts stated in document mentioned in section 161",
    "163": "Right of adverse party as to writing used to refresh memory",
    "164": "Production of documents",
    "165": "Giving, as evidence, of document called for and produced on notice",
    "166": "Using, as evidence, of document production of which was refused on notice",
    "167": "No new trial for improper admission or rejection of evidence"
}
