# CrPC (Code of Criminal Procedure, 1973 - Act 12)
# Authentic Bare Act Marginal Headings for Generic Sections

CRPC_TITLES = {
    # Constitution of Criminal Courts
    "21": "Special Executive Magistrates",
    "22": "Local Jurisdiction of Executive Magistrates",
    "23": "Subordination of Executive Magistrates",
    # Power of Courts
    "32": "Mode of conferring powers",
    "33": "Powers of officers appointed",
    "34": "Withdrawal of powers",
    "35": "Powers of Judges and Magistrates exercisable by their successors-in-office",
    # Powers of Superior Officers & Aid
    "36": "Powers of superior officers of police",
    "38": "Aid to person, other than police officer, executing warrant",
    "40": "Duty of officers employed in connection with the affairs of a village to make certain report",
    # Arrest of Persons
    "45": "Protection of members of the Armed Forces from arrest",
    "47": "Search of place entered by person sought to be arrested",
    "48": "Pursuit of offenders into other jurisdictions",
    "52": "Power to seize offensive weapons",
    "56": "Person arrested to be taken before Magistrate or officer in charge of police station",
    "59": "Discharge of person apprehended",
    "60": "Power, on escape, to pursue and retake",
    # Processes to Compel Appearance
    "63": "Service of summons on corporate bodies and societies",
    "64": "Service when persons summoned cannot be found",
    "65": "Procedure when service cannot be effected as before provided",
    "66": "Service on Government servant",
    "67": "Service of summons outside local limits",
    "68": "Proof of service in such cases and when serving officer not present",
    "69": "Service of summons on witness by post",
    "72": "Warrants to whom directed",
    "73": "Warrant may be directed to any person",
    "74": "Warrant directed to police officer",
    "75": "Notification of substance of warrant",
    "76": "Person arrested to be brought before Court without delay",
    "77": "Where warrant may be executed",
    "78": "Warrant forwarded for execution outside jurisdiction",
    "79": "Warrant directed to police officer for execution outside jurisdiction",
    "80": "Procedure on arrest of person against whom warrant issued",
    "81": "Procedure by Magistrate before whom such person arrested is brought",
    "84": "Claims and objections to attachment",
    "85": "Release, sale and restoration of attached property",
    "86": "Appeal from order rejecting application for restoration of attached property",
    "87": "Issue of warrant in lieu of, or in addition to, summons",
    "88": "Power to take bond for appearance",
    "89": "Arrest on breach of bond for appearance",
    "90": "Provisions of this Chapter generally applicable to summonses and warrants of arrest",
    # Processes to Compel Production of Things
    "92": "Procedure as to letters and telegrams",
    "94": "Search of place suspected to contain stolen property, forged documents, etc.",
    "95": "Power to declare certain publications forfeited and to issue search-warrants for the same",
    "96": "Application to High Court to set aside declaration of forfeiture",
    "97": "Search for persons wrongfully confined",
    "98": "Power to compel restoration of abducted females",
    "99": "Direction, etc., of search-warrants",
    "101": "Disposal of things found in search beyond jurisdiction",
    "103": "Magistrate may direct search in his presence",
    "104": "Power to impound document, etc., produced",
    # Reciprocal Arrangements
    "105": "Reciprocal arrangements regarding processes",
    "105B": "Assistance in securing transfer of persons",
    "105C": "Assistance in relation to orders of attachment or forfeiture of property",
    "105D": "Identifying unlawfully acquired property",
    "105E": "Seizure or attachment of property",
    "105F": "Management of properties seized or forfeited under this Chapter",
    "105G": "Notice of forfeiture of property",
    "105H": "Forfeiture of property in certain cases",
    "105I": "Fine in lieu of forfeiture",
    "105J": "Certain transfers to be null and void",
    "105K": "Procedure in respect of letter of request",
    "105L": "Application of this Chapter",
    # Security for Keeping Peace & Good Behaviour
    "106": "Security for keeping the peace on conviction",
    "111": "Order to be made",
    "112": "Procedure in respect of person present in Court",
    "113": "Summons or warrant in case of person not so present",
    "114": "Copy of order to accompany summons or warrant",
    "115": "Power to dispense with personal attendance",
    "116": "Inquiry as to truth of information",
    "117": "Order to give security",
    "118": "Discharge of person informed against",
    "119": "Commencement of period for which security is required",
    "120": "Contents of bond",
    "121": "Power to reject sureties",
    "122": "Imprisonment in default of security",
    "123": "Power to release persons imprisoned for failing to give security",
    "124": "Security for unexpired period of bond",
    # Public Order & Tranquillity
    "130": "Use of armed forces to disperse assembly",
    "131": "Power of certain armed force officers to disperse assembly",
    "132": "Protection against prosecution for acts done under preceding sections",
    "134": "Service or notification of order",
    "135": "Person to whom order is addressed to obey or show cause",
    "136": "Consequences of his failing to do so",
    "137": "Procedure where existence of public right is denied",
    "138": "Procedure where he appears to show cause",
    "139": "Power of Magistrate to direct local investigation and examination of an expert",
    "140": "Power of Magistrate to furnish written instructions, etc.",
    "141": "Procedure on order being made absolute and consequences of disobedience",
    "142": "Injunction pending inquiry",
    "143": "Magistrate may prohibit repetition or continuance of public nuisance",
    "144A": "Power to prohibit carrying arms in procession or mass drill or mass training with arms",
    "145": "Procedure where dispute concerning land or water is likely to cause breach of peace",
    "146": "Power to attach subject of dispute and to appoint receiver",
    "147": "Dispute concerning right of use of land or water",
    "148": "Local inquiry",
    # Preventive Action of Police
    "150": "Information of design to commit cognizable offences",
    "152": "Prevention of injury to public property",
    "153": "Inspection of weights and measures",
    # Investigation
    "158": "Report how submitted",
    "159": "Power to hold investigation or preliminary inquiry",
    "163": "No inducement to be offered",
    "165": "Search by police officer",
    "166": "When officer in charge of police station may require another to issue search-warrant",
    "168": "Report of investigation by subordinate police officer",
    "169": "Release of accused when evidence deficient",
    "170": "Cases to be sent to Magistrate, when evidence is sufficient",
    "171": "Complainant and witnesses not to be required to accompany police officer and not to be subjected to restraint",
    "175": "Power to summon persons",
    "176": "Inquiry by Magistrate into cause of death",
    # Jurisdiction in Inquiries & Trials
    "178": "Place of inquiry or trial",
    "179": "Offence triable where act is done or consequence ensues",
    "180": "Place of trial where act is an offence by reason of relation to other offence",
    "181": "Place of trial in case of certain offences",
    "182": "Offences committed by letters, etc.",
    "183": "Offence committed on journey or voyage",
    "184": "Place of trial for offences triable together",
    "185": "Power to order cases to be tried in different sessions divisions",
    "186": "High Court to decide, in case of doubt, district where inquiry or trial shall take place",
    "187": "Power to issue summons or warrant for offence committed beyond local jurisdiction",
    "188": "Offence committed outside India",
    "189": "Receipt of evidence relating to offences committed outside India",
    # Initiation of Proceedings
    "191": "Transfer on application of the accused",
    "192": "Making over of cases to Magistrates",
    "194": "Additional and Assistant Sessions Judges to try cases made over to them",
    "196": "Prosecution for offences against the State and for criminal conspiracy to commit such offence",
    "198A": "Prosecution of offences under section 498A of the Indian Penal Code",
    "199": "Prosecution for defamation",
    # Complaints to Magistrates
    "201": "Procedure by Magistrate not competent to take cognizance of the case",
    "203": "Dismissal of complaint",
    # Commencement of Proceedings
    "205": "Magistrate may dispense with personal attendance of accused",
    "206": "Special summons in case of petty offence",
    "208": "Supply of copies of statements and documents to accused in other cases triable by Court of Session",
    "210": "Procedure to be followed when there is a complaint case and police investigation in respect of the same offence",
    # The Charge
    "212": "Particulars as to time, place and person",
    "213": "When manner of committing offence must be stated",
    "214": "Words in charge taken in sense of law under which offence is punishable",
    "215": "Effect of errors",
    "217": "Recall of witnesses when charge altered",
    "218": "Separate charges for distinct offences",
    "219": "Three offences of same kind within year may be charged together",
    "220": "Trial for more than one offence",
    "221": "Where it is doubtful what offence has been committed",
    "222": "When offence proved included in offence charged",
    "223": "What persons may be charged jointly",
    "224": "Withdrawal of remaining charges on conviction on one of several charges",
    # Sessions Trial
    "225": "Trial to be conducted by Public Prosecutor",
    "226": "Opening case for prosecution",
    "229": "Conviction on plea of guilty",
    "230": "Date for prosecution evidence",
    "233": "Entering upon defence",
    "234": "Arguments",
    "236": "Previous conviction",
    "237": "Procedure in cases instituted under section 199(2)",
    # Warrant Cases by Magistrates
    "238": "Compliance with section 207",
    "241": "Conviction on plea of guilty",
    "242": "Evidence for prosecution",
    "243": "Evidence for defence",
    "244": "Evidence for prosecution (in cases instituted otherwise than on police report)",
    "245": "When accused shall be discharged",
    "246": "Procedure where accused is not discharged",
    "247": "Evidence for defence",
    "248": "Acquittal or conviction",
    "249": "Absence of complainant",
    "250": "Compensation for accusation without reasonable cause",
    # Summons Cases by Magistrates
    "252": "Conviction on plea of guilty",
    "253": "Conviction on plea of guilty in absence of accused in petty cases",
    "254": "Procedure when not convicted",
    "255": "Acquittal or conviction",
    "257": "Withdrawal of complaint",
    "258": "Power to stop proceedings in certain cases",
    "259": "Power of Court to convert summons-cases into warrant-cases",
    # Summary Trials
    "261": "Summary trial by Magistrate of the second class",
    "262": "Procedure for summary trials",
    "263": "Record in summary trials",
    "264": "Judgment in cases tried summarily",
    # Plea Bargaining
    "265": "Application of the Chapter",
    "265B": "Application for plea bargaining",
    "265C": "Guidelines for mutually satisfactory disposition",
    "265D": "Report of the mutually satisfactory disposition to be submitted before the Court",
    "265E": "Disposal of the case",
    "265F": "Judgment of the Court",
    "265G": "Finality of the judgment",
    "265H": "Power of the Court in plea bargaining",
    "265I": "Period of detention undergone by the accused to be set off against the sentence of imprisonment",
    "265J": "Savings",
    "265K": "Statements of accused not to be used",
    "265L": "Non-application of the Chapter",
    # Attendance of Prisoners
    "266": "Definitions",
    "267": "Power to require attendance of prisoners",
    "268": "Power of State Government to exclude certain persons from operation of section 267",
    "269": "Officer in charge of prison to abstain from carrying out order in certain contingencies",
    "270": "Prisoner to be brought to Court in custody",
    "271": "Power to issue commission for examination of witness in prison",
    # Evidence in Inquiries & Trials
    "272": "Language of Courts",
    "273": "Evidence to be taken in presence of accused",
    "274": "Record in summons-cases and inquiries",
    "275": "Record in warrant-cases",
    "276": "Record in trial before Court of Session",
    "277": "Language of record of evidence",
    "278": "Procedure in regard to such evidence when completed",
    "279": "Interpretation of evidence to accused or his pleader",
    "280": "Remarks respecting demeanour of witness",
    "281": "Record of examination of accused",
    "282": "Interpreter to be bound to interpret truthfully",
    "283": "Record in High Court",
    "284": "When attendance of witness may be dispensed with and commission issued",
    "285": "Commission to whom to be issued",
    "286": "Execution of commissions",
    "287": "Parties may examine witnesses",
    "288": "Return of commission",
    "289": "Adjournment of proceeding",
    "290": "Execution of foreign commissions",
    "291": "Deposition of medical witness",
    "291A": "Identification report of Magistrate",
    "292": "Evidence of officers of the Mint",
    "293": "Reports of certain Government scientific experts",
    "294": "No formal proof of certain documents",
    "295": "Affidavit in proof of conduct of public servants",
    "296": "Evidence of formal character on affidavit",
    "297": "Authorities before whom affidavits may be sworn",
    "298": "Previous conviction or acquittal how proved",
    "299": "Record of evidence in absence of accused",
    # General Provisions as to Inquiries & Trials
    "301": "Appearance by Public Prosecutors",
    "303": "Right of person against whom proceedings are instituted to be defended",
    "305": "Procedure when corporation or registered society is an accused",
    "306": "Tender of pardon to accomplice",
    "307": "Power to direct tender of pardon",
    "308": "Trial of person not complying with conditions of pardon",
    "310": "Local inspection",
    "312": "Expenses of complainants and witnesses",
    "314": "Oral arguments and memorandum of arguments",
    "315": "Accused person to be competent witness",
    "316": "No influence to be used to induce disclosure",
    "317": "Provision for inquiries and trial being held in the absence of accused in certain cases",
    "318": "Procedure where accused does not understand proceedings",
    "319": "Power to proceed against other persons appearing to be guilty of offence",
    "322": "Procedure in cases which Magistrate cannot dispose of",
    "323": "Procedure when, after Commencement of inquiry or trial, Magistrate finds case should be committed",
    "324": "Trial of persons previously convicted of offences against coinage, stamp-law or property",
    "325": "Procedure when Magistrate cannot pass sentence sufficiently severe",
    "326": "Conviction or commitment on evidence partly recorded by one Magistrate and partly by another",
    "327": "Court to be open",
    # Accused Persons of Unsound Mind
    "328": "Procedure in case of accused being lunatic",
    "329": "Procedure in case of person of unsound mind tried before Court",
    "330": "Release of person of unsound mind pending investigation or trial",
    "331": "Resumption of inquiry or trial",
    "332": "Procedure on accused appearing before Magistrate or Court",
    "333": "When accused appears to have been of sound mind",
    "334": "Judgment of acquittal on ground of unsoundness of mind",
    "335": "Person acquitted on such ground to be detained in safe custody",
    "336": "Power of State Government to empower officer in charge to discharge",
    "337": "Procedure where lunatic prisoner is reported capable of making his defence",
    "338": "Procedure where lunatic detained is declared fit to be released",
    "339": "Delivery of lunatic to care of relative or friend",
    # Offences Affecting Administration of Justice
    "340": "Procedure in cases mentioned in section 195",
    "341": "Appeal",
    "342": "Power to order costs",
    "343": "Procedure of Magistrate taking cognizance",
    "344": "Summary procedure for trial for giving false evidence",
    "345": "Procedure in certain cases of contempt",
    "346": "Procedure where Court considers that case should not be dealt with under section 345",
    "347": "When Registrar or Sub-Registrar to be deemed a Civil Court",
    "348": "Discharge of offender on submission of apology",
    "349": "Imprisonment or committal of person refusing to answer or produce document",
    "350": "Summary procedure for punishment for non-attendance by a witness in obedience to summons",
    "351": "Appeals from convictions under sections 344, 345, 349 and 350",
    "352": "Certain Judges and Magistrates not to try certain offences when committed before themselves",
    # The Judgment
    "355": "Metropolitan Magistrate's judgment",
    "356": "Order for notifying address of previously convicted offender",
    "357B": "Compensation to be in addition to fine under section 326A or section 376D of Indian Penal Code",
    "357C": "Treatment of victims",
    "358": "Compensation to persons groundlessly arrested",
    "359": "Order to pay costs in non-cognizable cases",
    "360": "Order to release on probation of good conduct or after admonition",
    "361": "Special reasons to be recorded in certain cases",
    "362": "Court not to alter judgment",
    "363": "Copy of judgment to be given to the accused and other persons",
    "364": "Judgment when to be translated",
    "365": "Court of Session to send copy of finding and sentence to District Magistrate",
    # Confirmation of Death Sentences
    "367": "Power to direct further inquiry to be made or additional evidence to be taken",
    "368": "Power of High Court to confirm sentence or annul conviction",
    "369": "Confirmation or new sentence to be signed by two Judges",
    "370": "Procedure in case of difference of opinion",
    "371": "Procedure in cases submitted to High Court for confirmation",
    # Appeals
    "373": "Appeal from orders requiring security or refusal to accept or rejecting surety for keeping peace or good behaviour",
    "375": "No appeal in certain cases when accused pleads guilty",
    "376": "No appeal in petty cases",
    "377": "Appeal by the State Government against sentence",
    "379": "Appeal against conviction by High Court in certain cases",
    "380": "Special right of appeal in certain cases",
    "381": "Appeal to Court of Session how heard",
    "382": "Petition of appeal",
    "383": "Procedure when appellant in jail",
    "384": "Summary dismissal of appeal",
    "385": "Procedure for hearing appeals not dismissed summarily",
    "386": "Powers of the Appellate Court",
    "387": "Judgments of Subordinate Appellate Court",
    "388": "Order of High Court on appeal to be certified to lower Court",
    "389": "Suspension of sentence pending the appeal; release of appellant on bail",
    "390": "Arrest of accused in appeal from acquittal",
    "391": "Appellate Court may take further evidence or direct it to be taken",
    "392": "Procedure where Judges of Court of Appeal are equally divided",
    "393": "Finality of judgments and orders on appeal",
    "394": "Abatement of appeals",
    # Reference and Revision
    "395": "Reference to High Court",
    "396": "Disposal of case according to decision of High Court",
    "398": "Power to order inquiry",
    "399": "Sessions Judge's powers of revision",
    "400": "Power of Additional Sessions Judge",
    "402": "Power of High Court to withdraw or transfer revision cases",
    "403": "Option of Court to hear parties",
    "404": "Statement by Metropolitan Magistrate of grounds of his decision to be considered by High Court",
    "405": "High Court's order to be certified to lower Court",
    # Transfer of Cases
    "408": "Power of Sessions Judge to transfer cases and appeals",
    "409": "Withdrawal of cases and appeals by Sessions Judge",
    "410": "Withdrawal of cases by Judicial Magistrates",
    "411": "Making over or withdrawal of cases by Executive Magistrates",
    "412": "Reasons to be recorded",
    # Execution of Sentences
    "413": "Execution of order passed under section 368",
    "414": "Execution of sentence of death passed by High Court",
    "415": "Postponement of execution of sentence of death in case of appeal to Supreme Court",
    "416": "Postponement of capital sentence on pregnant woman",
    "417": "Power to appoint place of imprisonment",
    "418": "Execution of sentence of imprisonment",
    "419": "Direction of warrant for execution",
    "420": "Warrant with whom to be lodged",
    "421": "Warrant for levy of fine",
    "422": "Effect of such warrant",
    "423": "Warrant for levy of fine issued by a Court in any territory to which this Code does not extend",
    "424": "Suspension of execution of sentence of imprisonment",
    "425": "Who may issue warrant",
    "426": "Sentence on escaped convict when to take effect",
    "427": "Sentence on offender already sentenced for another offence",
    "428": "Period of detention undergone by the accused to be set off against the sentence of imprisonment",
    "429": "Saving",
    "430": "Return of warrant on execution of sentence",
    "431": "Money ordered to be paid recoverable as a fine",
    "432": "Power to suspend or remit sentences",
    "433": "Power to commute sentence",
    "434": "Concurrent power of Central Government in case of death sentences",
    "435": "State Government to act after consultation with Central Government in certain cases",
    # Bail and Bonds
    "440": "Amount of bond and reduction thereof",
    "441": "Bond of accused and sureties",
    "442": "Discharge from custody",
    "443": "Power to order sufficient bail when that first taken is insufficient",
    "444": "Discharge of sureties",
    "445": "Deposit instead of recognizance",
    "447": "Procedure in case of insolvency or death of surety or when a bond is forfeited",
    "448": "Bond required from minor",
    "449": "Appeal from orders under section 446",
    "450": "Power to direct levy of amount due on certain recognizances",
    # Disposal of Property
    "452": "Order for disposal of property at conclusion of trial",
    "453": "Payment to innocent purchaser of money found on accused",
    "454": "Appeal against orders under section 452 or section 453",
    "455": "Destruction of libellous and other matter",
    "456": "Power to restore possession of immovable property",
    "457": "Procedure by police upon seizure of property",
    "458": "Procedure where no claimant appears within six months",
    "459": "Power to sell perishable property",
    # Irregular Proceedings
    "460": "Irregularities which do not vitiate proceedings",
    "461": "Irregularities which vitiate proceedings",
    "462": "Proceedings in wrong place",
    "463": "Non-compliance with provisions of section 164 or section 281",
    "464": "Effect of omission to frame, or absence of, or error in, charge",
    "465": "Finding or sentence when reversible by reason of error, omission or irregularity",
    "466": "Defect or want of form in proceedings",
    # Limitation
    "467": "Definitions",
    "469": "Commencement of the period of limitation",
    "470": "Exclusion of time in certain cases",
    "471": "Exclusion of date on which Court is closed",
    "472": "Continuing offence",
    "473": "Extension of period of limitation in certain cases",
    # Miscellaneous
    "474": "Trials before High Courts",
    "475": "Delivery to commanding officers of persons liable to be tried by Court-martial",
    "476": "Forms",
    "477": "Power of High Court to make rules",
    "478": "Power to alter functions allocated to Executive Magistrates in certain cases",
    "479": "Case in which Judge or Magistrate is personally interested",
    "480": "Practising pleader not to sit as Magistrate in certain Courts",
    "481": "Public servant concerned in sale not to purchase or bid for property",
    "483": "Duty of High Court to exercise continuous superintendence over Courts of Judicial Magistrates"
}
