# IEA (Indian Evidence Act, 1872 - Act 13)
# Authentic Bare Act Marginal Headings for Generic Sections

IEA_TITLES = {
    "12": "In suits for damages, facts tending to enable Court to determine amount are relevant",
    "13": "Facts relevant when right or custom is in question",
    "15": "Facts bearing on question whether act was accidental or intentional",
    "16": "Existence of course of business when relevant",
    "18": "Admission by party to proceeding or his agent",
    "19": "Admissions by persons whose position must be proved as against party to suit",
    "20": "Admissions by persons expressly referred to by party to suit",
    "22": "When oral admissions as to contents of documents are relevant",
    "22A": "When oral admission as to contents of electronic records are relevant",
    "23": "Admissions in civil cases, when relevant",
    "29": "Confession otherwise relevant not to become irrelevant because of promise of secrecy, etc.",
    "31": "Admissions not conclusive proof, but may estop",
    "34": "Entries in books of account including those maintained in an electronic form when relevant",
    "35": "Relevancy of entry in public record made in performance of duty",
    "36": "Relevancy of statements in maps, charts and plans",
    "37": "Relevancy of statement as to fact of public nature contained in certain Acts or notifications",
    "38": "Relevancy of statements as to any law contained in law-books",
    "39": "What evidence to be given when statement forms part of a conversation, document, electronic record, book or series of letters or papers",
    "40": "Previous judgments relevant to bar a second suit or trial (Res Judicata)",
    "41": "Relevancy of certain judgments in probate, etc., jurisdiction (Judgments in rem)",
    "42": "Relevancy and effect of judgments, orders or decrees, other than those mentioned in section 41",
    "43": "Judgments, etc., other than those mentioned in sections 40 to 42, when relevant",
    "44": "Fraud or collusion in obtaining judgment, or incompetency of Court, may be proved",
    "46": "Facts bearing upon opinions of experts",
    "48": "Opinion as to existence of right or custom, when relevant",
    "49": "Opinion as to usages, tenets, etc., when relevant",
    "50": "Opinion on relationship, when relevant",
    "51": "Grounds of opinion, when relevant",
    "52": "In civil cases character to prove conduct imputed, irrelevant",
    "55": "Character as affecting damages",
    "66": "Rules as to notice to produce",
    "68": "Proof of execution of document required by law to be attested",
    "69": "Proof where no attesting witness found",
    "70": "Admission of execution by party to attested document",
    "71": "Proof when attesting witness denies the execution",
    "72": "Proof of document not required by law to be attested",
    "77": "Proof of documents by production of certified copies",
    "78": "Proof of other official documents",
    "80": "Presumption as to documents produced as record of evidence",
    "81": "Presumption as to Gazettes, newspapers, private Acts of Parliament and other documents",
    "81A": "Presumption as to Gazettes in electronic forms",
    "82": "Presumption as to document admissible in England without proof of seal or signature",
    "83": "Presumption as to maps or plans made by authority of Government",
    "84": "Presumption as to collections of laws and reports of decisions",
    "85": "Presumption as to powers-of-attorney",
    "86": "Presumption as to certified copies of foreign judicial records",
    "87": "Presumption as to books, maps and charts",
    "88": "Presumption as to telegraphic messages",
    "88A": "Presumption as to electronic messages",
    "89": "Presumption as to due execution, etc., of documents not produced",
    "93": "Exclusion of evidence to explain or amend ambiguous document",
    "94": "Exclusion of evidence against application of document to existing facts",
    "95": "Evidence as to document unmeaning in reference to existing facts",
    "96": "Evidence as to application of language which can apply to one only of several persons",
    "97": "Evidence as to application of language to one of two sets of facts, to neither of which the whole correctly applies",
    "98": "Evidence as to meaning of illegible characters, etc.",
    "99": "Who may give evidence of agreement varying terms of document",
    "100": "Saving of provisions of Indian Succession Act relating to wills",
    "109": "Burden of proof as to relationship in the cases of partners, landlord and tenant, principal and agent",
    "110": "Burden of proof as to ownership",
    "111": "Proof of good faith in transactions where one party is in relation of active confidence",
    "113": "Proof of cession of territory",
    "117": "Estoppel of acceptor of bill of exchange, bailee or licensee",
    "121": "Dumb witnesses / Judges and Magistrates",
    "127": "Section 126 to apply to interpreters, etc.",
    "128": "Privilege not waived by volunteering evidence",
    "129": "Confidential communications with legal advisers",
    "130": "Production of title-deeds of witness not a party",
    "131": "Production of documents or electronic records which another person, having possession, could refuse to produce",
    "139": "Cross-examination of person called to produce a document",
    "140": "Witnesses to character",
    "144": "Evidence as to matters in writing",
    "147": "When witness to be compelled to answer",
    "148": "Court to decide when question shall be asked and when witness compelled to answer",
    "149": "Question not to be asked without reasonable grounds",
    "150": "Procedure of Court in case of question being asked without reasonable grounds",
    "151": "Indecent and scandalous questions",
    "152": "Questions intended to insult or annoy",
    "153": "Exclusion of evidence to contradict answers to questions testing veracity",
    "156": "Questions tending to corroborate evidence of relevant fact, admissible",
    "158": "What matters may be proved in connection with proved statement relevant under section 32 or 33",
    "160": "Testimony to facts stated in document mentioned in section 159",
    "161": "Right of adverse party as to writing used to refresh memory",
    "162": "Production of documents",
    "163": "Giving, as evidence, of document called for and produced on notice",
    "164": "Using, as evidence, of document production of which was refused on notice",
    "166": "Power of jury or assessors to put questions"
}
