# IPC (Indian Penal Code, 1860 - Act 11)
# Authentic Bare Act Marginal Headings for Generic Sections

IPC_TITLES = {
    "56": "Sentence of Europeans and Americans to penal servitude (Repealed)",
    "58": "Europeans and Americans to be sentenced to penal servitude (Repealed)",
    "59": "Transportation instead of imprisonment (Repealed)",
    "61": "Sentence of forfeiture of property (Repealed)",
    "62": "Forfeiture of property, in respect of offenders punishable with death, transportation or imprisonment (Repealed)",
    "68": "Imprisonment to terminate on payment of fine",
    "69": "Termination of imprisonment on payment of proportional part of fine",
    "126": "Committing depredation on territories of Power at peace with the Government of India",
    "127": "Receiving property taken by war or depredation mentioned in sections 125 and 126",
    "129": "Public servant negligently suffering prisoner of State or war to escape",
    "131": "Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty",
    "132": "Abetment of mutiny, if mutiny is committed in consequence thereof",
    "133": "Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office",
    "134": "Abetment of such assault, if the assault is committed",
    "135": "Abetment of desertion of soldier, sailor or airman",
    "136": "Harbouring deserter",
    "137": "Deserter concealed on board merchant vessel through negligence of master",
    "138": "Abetment of act of insubordination by soldier, sailor or airman",
    "139": "Persons subject to certain Acts not punishable under this Code",
    "140": "Wearing garb or carrying token used by soldier, sailor or airman",
    "154": "Owner or occupier of land on which an unlawful assembly is held",
    "155": "Liability of person for whose benefit riot is committed",
    "156": "Liability of agent of owner or occupier for whose benefit riot is committed",
    "157": "Harbouring persons hired for an unlawful assembly",
    "158": "Being hired to take part in an unlawful assembly or riot",
    "162": "Taking gratification, in order, by corrupt or illegal means, to influence public servant (Repealed)",
    "163": "Taking gratification, for exercise of personal influence with public servant (Repealed)",
    "164": "Punishment for abetment by public servant of offences defined in section 162 or 163 (Repealed)",
    "165": "Public servant obtaining valuable thing, without consideration, from person concerned in proceeding or business transacted by such public servant (Repealed)",
    "168": "Public servant unlawfully engaging in trade",
    "169": "Public servant unlawfully buying or bidding for property",
    "170": "Personating a public servant",
    "171": "Wearing garb or carrying token used by public servant with fraudulent intent",
    "176": "Omission to give notice or information to public servant by person legally bound to give it",
    "178": "Refusing oath or affirmation when duly required by public servant to make it",
    "179": "Refusing to answer public servant authorized to question",
    "180": "Refusing to sign statement",
    "181": "False statement on oath or affirmation to public servant or person authorized to administer an oath",
    "183": "Resistance to the taking of property by the lawful authority of a public servant",
    "184": "Obstructing sale of property offered for sale by authority of public servant",
    "185": "Illegal purchase or bid for property offered for sale by authority of public servant",
    "189": "Threat of injury to public servant",
    "190": "Threat of injury to induce person to refrain from applying for protection to public servant",
    "196": "Using evidence known to be false",
    "197": "Issuing or signing false certificate",
    "198": "Using as true a certificate known to be false",
    "199": "False statement made in declaration which is by law receivable as evidence",
    "200": "Using as true such declaration knowing it to be false",
    "203": "Giving false information respecting an offence committed",
    "205": "False personation for purpose of act or proceeding in suit or prosecution",
    "206": "Fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution",
    "207": "Fraudulent claim to property to prevent its seizure as forfeited or in execution",
    "208": "Fraudulently suffering decree for sum not due",
    "209": "Dishonestly making false claim in Court",
    "210": "Fraudulently obtaining decree for sum not due",
    "213": "Taking gift, etc., to screen an offender from punishment",
    "214": "Offering gift or restoration of property in consideration of screening offender",
    "215": "Taking gift to help to recover stolen property, etc.",
    "217": "Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture",
    "218": "Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture",
    "219": "Public servant in judicial proceeding corruptly making report, etc., contrary to law",
    "220": "Commitment for trial or confinement by person having authority who knows that he is acting contrary to law",
    "221": "Intentional omission to apprehend on the part of public servant bound to apprehend",
    "222": "Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence or lawfully committed",
    "223": "Escape from confinement or custody negligently suffered by public servant",
    "224": "Resistance or obstruction by a person to his lawful apprehension",
    "225": "Resistance or obstruction to lawful apprehension of another person",
    "226": "Unlawful return from transportation (Repealed)",
    "227": "Violation of condition of remission of punishment",
    "229": "Personation of a juror or assessor",
    "230": "\"Coin\" defined",
    "231": "Counterfeiting coin",
    "232": "Counterfeiting Indian coin",
    "233": "Making or selling instrument for counterfeiting coin",
    "234": "Making or selling instrument for counterfeiting Indian coin",
    "235": "Possession of instrument or material for the purpose of using the same for counterfeiting coin",
    "236": "Abetting in India the counterfeiting out of India of coin",
    "237": "Import or export of counterfeit coin",
    "238": "Import or export of counterfeits of the Indian coin",
    "239": "Delivery of coin, possessed with the knowledge that it is counterfeit",
    "240": "Delivery of Indian coin, possessed with the knowledge that it is counterfeit",
    "241": "Delivery of coin as genuine, which, when first possessed, the deliverer did not know to be counterfeit",
    "242": "Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof",
    "243": "Possession of Indian coin by person who knew it to be counterfeit when he became possessed thereof",
    "244": "Person employed in mint causing coin to be of different weight or composition from that fixed by law",
    "245": "Unlawfully taking coining instrument from mint",
    "246": "Fraudulently or dishonestly diminishing weight or altering composition of coin",
    "247": "Fraudulently or dishonestly diminishing weight or altering composition of Indian coin",
    "248": "Altering appearance of coin with intent that it shall pass as coin of different description",
    "249": "Altering appearance of Indian coin with intent that it shall pass as coin of different description",
    "250": "Delivery of coin, possessed with knowledge that it is altered",
    "251": "Delivery of Indian coin, possessed with knowledge that it is altered",
    "252": "Possession of coin by person who knew it to be altered when he became possessed thereof",
    "253": "Possession of Indian coin by person who knew it to be altered when he became possessed thereof",
    "254": "Delivery of coin as genuine which, when first possessed, the deliverer did not know to be altered",
    "255": "Counterfeiting Government stamp",
    "256": "Having possession of instrument or material for counterfeiting Government stamp",
    "257": "Making or selling instrument for counterfeiting Government stamp",
    "258": "Sale of counterfeit Government stamp",
    "259": "Having possession of counterfeit Government stamp",
    "260": "Using as genuine a Government stamp known to be a counterfeit",
    "261": "Effacing writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government",
    "262": "Using Government stamp known to have been before used",
    "263": "Erasure of mark denoting that stamp has been used",
    "264": "Fraudulent use of false instrument for weighing",
    "265": "Fraudulent use of false weight or measure",
    "266": "Being in possession of false weight or measure",
    "267": "Making or selling false weight or measure",
    "271": "Disobedience to quarantine rule",
    "274": "Adulteration of drugs",
    "275": "Sale of adulterated drugs",
    "276": "Sale of drug as a different drug or preparation",
    "278": "Making atmosphere noxious to health",
    "281": "Exhibition of false light, mark or buoy",
    "282": "Conveying person by water for hire in unsafe or overloaded vessel",
    "284": "Negligent conduct with respect to poisonous substance",
    "286": "Negligent conduct with respect to explosive substance",
    "287": "Negligent conduct with respect to machinery",
    "288": "Negligent conduct with respect to pulling down or repairing buildings",
    "291": "Continuance of nuisance after injunction to discontinue",
    "293": "Sale, etc., of obscene objects to young person",
    "296": "Disturbing religious assembly",
    "297": "Trespassing on burial places, etc.",
    "329": "Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act",
    "330": "Voluntarily causing hurt to extort confession, or to compel restoration of property",
    "331": "Voluntarily causing grievous hurt to extort confession, or to compel restoration of property",
    "334": "Voluntarily causing hurt on provocation",
    "335": "Voluntarily causing grievous hurt on provocation",
    "343": "Wrongful confinement for three or more days",
    "344": "Wrongful confinement for ten or more days",
    "345": "Wrongful confinement of person for whose liberation writ has been issued",
    "346": "Wrongful confinement in secret",
    "347": "Wrongful confinement to extort property, or constrain to illegal act",
    "348": "Wrongful confinement to extort confession, or compel restoration of property",
    "355": "Assault or criminal force with intent to dishonour person, otherwise than on grave provocation",
    "356": "Assault or criminal force in attempt to commit theft of property carried by a person",
    "357": "Assault or criminal force in attempt wrongfully to confine a person",
    "358": "Assault or criminal force on grave provocation",
    "367": "Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc.",
    "368": "Wrongfully concealing or keeping in confinement, kidnapped or abducted person",
    "369": "Kidnapping or abducting child under ten years with intent to steal from its person",
    "371": "Habitual dealing in slaves",
    "372": "Selling minor for purposes of prostitution, etc.",
    "373": "Buying minor for purposes of prostitution, etc.",
    "374": "Unlawful compulsory labour",
    "387": "Putting person in fear of death or of grievous hurt, in order to commit extortion",
    "388": "Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc.",
    "389": "Putting person in fear of accusation of offence, in order to commit extortion",
    "401": "Punishment for belonging to gang of thieves",
    "413": "Habitually dealing in stolen property",
    "414": "Assisting in concealment of stolen property",
    "421": "Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors",
    "422": "Dishonestly or fraudulently preventing debt being made available for creditors",
    "423": "Dishonest or fraudulent execution of deed of transfer containing false statement of consideration",
    "424": "Dishonest or fraudulent removal or concealment of property",
    "428": "Mischief by killing or maiming animal of the value of ten rupees",
    "429": "Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees",
    "430": "Mischief by injury to works of irrigation or by wrongfully diverting water",
    "431": "Mischief by injury to public road, bridge, navigable river or navigable channel, and rendering it impassable",
    "432": "Mischief by causing inundation or obstruction to public drainage attended with damage",
    "433": "Mischief by destroying, moving or rendering less useful a light-house or sea-mark",
    "434": "Mischief by destroying or moving, etc., a landmark fixed by public authority",
    "437": "Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden",
    "438": "Punishment for the mischief described in section 437 committed by fire or explosive substance",
    "439": "Punishment for intentionally running vessel aground or ashore with intent to commit theft, etc.",
    "440": "Mischief committed after preparation made for causing death or hurt",
    "443": "Lurking house-trespass",
    "444": "Lurking house-trespass by night",
    "445": "House-breaking",
    "446": "House-breaking by night",
    "449": "House-trespass in order to commit offence punishable with death",
    "450": "House-trespass in order to commit offence punishable with imprisonment for life",
    "453": "Punishment for lurking house-trespass or house-breaking",
    "454": "Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment",
    "455": "Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint",
    "456": "Punishment for lurking house-trespass or house-breaking by night",
    "458": "Lurking house-trespass or house-breaking by night after preparation for hurt, assault, or wrongful restraint",
    "459": "Grievous hurt caused whilst committing lurking house-trespass or house-breaking",
    "460": "All persons jointly concerned in lurking house-trespass or house-breaking by night punishable where death or grievous hurt caused by one of them",
    "461": "Dishonestly breaking open receptacle containing property",
    "462": "Punishment for same offence when committed by person entrusted with custody",
    "466": "Forgery of record of Court or of public register, etc.",
    "469": "Forgery for purpose of harming reputation",
    "470": "Forged document or electronic record",
    "472": "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under section 467",
    "473": "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise",
    "474": "Having possession of document described in section 466 or 467, knowing it to be forged and intending to use it as genuine",
    "475": "Counterfeiting device or mark used for authenticating documents described in section 467, or possessing counterfeit marked material",
    "476": "Counterfeiting device or mark used for authenticating documents other than those described in section 467, or possessing counterfeit marked material",
    "477": "Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security",
    "478": "Trade mark (Repealed)",
    "479": "Property mark",
    "480": "Using a false trade mark (Repealed)",
    "481": "Using a false property mark",
    "482": "Punishment for using a false property mark",
    "483": "Counterfeiting a property mark used by another",
    "484": "Counterfeiting a mark used by a public servant",
    "485": "Making or possession of any instrument for counterfeiting a property mark",
    "486": "Selling goods marked with a counterfeit property mark",
    "487": "Making a false mark upon any receptacle containing goods",
    "488": "Punishment for making use of any such false mark",
    "489": "Tampering with property mark with intent to cause injury",
    "489D": "Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes",
    "489E": "Making or using documents resembling currency-notes or bank-notes",
    "490": "Breach of contract of service during voyage or journey (Repealed)",
    "491": "Breach of contract to attend on and supply wants of helpless person",
    "492": "Breach of contract to serve at distant place to which servant is conveyed at master's expense (Repealed)",
    "505": "Statements conducing to public mischief",
    "507": "Criminal intimidation by an anonymous communication",
    "508": "Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure"
}
